export const LOGIN_SUCCESSFUL = 'LOGIN_SUCCESSFUL'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const FETCH_AUTH = 'FETCH_AUTH'
export const CHANGE_PASSWORD_FIELD = "CHANGE_PASSWORD_FIELD"
export const CHANGE_EMAIL_FIELD = "CHANGE_EMAIL_FIELD"